### ISSUE TITLE
Pip install requirements file

### ISSUE THREAD

**Issue by vijender412** [JulianGerhard21/bert_spacy_rasa#2]
Collecting torch>=1.0.0 (from spacy-transformers==0.5.1)
  ERROR: Could not find a version that satisfies the requirement torch>=1.0.0 (from spacy-transformers==0.5.1) (from versions: 0.1.2, 0.1.2.post1, 0.1.2.post2)
ERROR: No matching distribution found for torch>=1.0.0 (from spacy-transformers==0.5.1)

**Comment by JulianGerhard21** [comment]
Hi @vijender412 ,

this is a known problem that may happen. Depending on your operating system try:

**Windows**
`python3 -m pip install https://download.pytorch.org/whl/cpu/torch-1.3.0%2Bcpu-cp36-cp36m-win_amd64.whl`

**Linux**
`python3 -m pip install https://download.pytorch.org/whl/cpu/torch-1.3.0%2Bcpu-cp36-cp36m-linux_x86_64.whl`

Keep in mind to use the correct python executable.

Kind regards
Julian

**Comment by vijender412** [comment]
Thanks Julian,

I fixed that issue by install pytorch with `pip3 install torch===1.3.1 torchvision===0.4.2 -f https://download.pytorch.org/whl/torch_stable.html`

Also I have created my first sentiment analysis with bert with help of your repo. Thanks alot for sharing.

Few issues I faced were 
1.  File "pipes.pyx", in spacy.pipeline.pipes.Pipe.from_disk.load_model ValueError: [E149] Error deserializing model. Check that the config used to create the component matches the model being loaded.
Which got fixed by changing meta.json trf_text_cat:trf_textcat

2. Used English model "en_trf_bertbaseuncased_lg" after fine-tuning it and changing name & packing it. The model doesn't show in "`python -m spacy validate`" command. But it works no issue.
3. While retraining it the process is taking a long time and iternation never end in my case. Changed patience to 1 as I was getting high accuracy at first 3 iteration.
--

Thanks again for sharing keep updating.

**Comment by JulianGerhard21** [comment]
Hi @vijender412 ,

thanks a lot for sharing your thoughts. Youre welcome! The trf_textcat is also known but unfortunately I didnt have the time to describe it in README.md. I hope that the PRs from spacy-transformers will soon be merged such that manually editting files is no longer necessary. 

Regarding point 2: I wondered from the beginning why this doesnt happen and I think it is due the fintuned models are not properly registered in the model domain of spacy. Maybe we should open an Issue here.

Thanks again! 

Regards
Julian
